Members only
AlejandroNo4/members-only pull request #1
Opened 2021-03-17 19:58 UTC by AlejandroNo4

This project was made for learning proposes, to implement authentication systems using Ruby On Rails, so users can only access areas of a site they are authorized to.

2021-03-17 21:31 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @AlejandroNo4 :clap: :clap:
#### You have done a good job :muscle: However, you need to implement some minor changes before this project can be approved. Check my comments below :point_down:

#### 1) Readme:
 - Add instruction on how to run the migration
 
#### 2) View & Logic:
 - There should be no logic in the view. Move any view logic to the helper.

#### _Reviewed by Temitayo Adeleke_

2021-03-17 21:31 UTC, lekegitrepo commented on app/views/home/index.html.erb
> +      <% end %>
- Remove logic from the view

2021-03-17 21:31 UTC, lekegitrepo commented on app/views/shared/_navbar.html.erb
> +        <% end %>
- Remove logic from the view

2021-03-18 00:48 UTC, mke2111 approved these changes
# STATUS: APPROVED ㊗️ 🟡 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

2021-03-19 16:18 UTC, merged